INSERT [dbo].[RegistroUsuario] ([ID_Usuario], [Nombre], [Correo], [Contrasena], [Rol]) VALUES (1, N'Miguel Herrera', N'miguel.herrera@brainbro.com', N'est004', N'Estudiante')
INSERT [dbo].[RegistroUsuario] ([ID_Usuario], [Nombre], [Correo], [Contrasena], [Rol]) VALUES (2, N'Sebastian Castro', N'sebastian.castro@brainbro.com', N'est006', N'Estudiante')
INSERT [dbo].[RegistroUsuario] ([ID_Usuario], [Nombre], [Correo], [Contrasena], [Rol]) VALUES (3, N'Juan Perez', N'juan.perez@brainbro.com', N'est002', N'Estudiante')
INSERT [dbo].[RegistroUsuario] ([ID_Usuario], [Nombre], [Correo], [Contrasena], [Rol]) VALUES (4, N'Daniel Morales', N'daniel.morales@brainbro.com', N'est008', N'Estudiante')
INSERT [dbo].[RegistroUsuario] ([ID_Usuario], [Nombre], [Correo], [Contrasena], [Rol]) VALUES (5, N'Isabella Gomez', N'isabella.gomez@brainbro.com', N'est005', N'Estudiante')
INSERT [dbo].[RegistroUsuario] ([ID_Usuario], [Nombre], [Correo], [Contrasena], [Rol]) VALUES (6, N'Mariana Jimenez', N'mariana.jimenez@brainbro.com', N'est009', N'Estudiante')
INSERT [dbo].[RegistroUsuario] ([ID_Usuario], [Nombre], [Correo], [Contrasena], [Rol]) VALUES (7, N'Sofia Ramirez', N'sofia.ramirez@brainbro.com', N'est001', N'Estudiante')
INSERT [dbo].[RegistroUsuario] ([ID_Usuario], [Nombre], [Correo], [Contrasena], [Rol]) VALUES (8, N'Camila Vargas', N'camila.vargas@brainbro.com', N'est007', N'Estudiante')
INSERT [dbo].[RegistroUsuario] ([ID_Usuario], [Nombre], [Correo], [Contrasena], [Rol]) VALUES (9, N'Valentina Torres', N'valentina.torres@brainbro.com', N'est003', N'Estudiante')
INSERT [dbo].[RegistroUsuario] ([ID_Usuario], [Nombre], [Correo], [Contrasena], [Rol]) VALUES (11, N'Andres Rojas', N'andres.rojas@brainbro.com', N'prof002', N'Profesor')
INSERT [dbo].[RegistroUsuario] ([ID_Usuario], [Nombre], [Correo], [Contrasena], [Rol]) VALUES (12, N'Ricardo Lopez', N'ricardo.lopez@brainbro.com', N'prof004', N'Profesor')
INSERT [dbo].[RegistroUsuario] ([ID_Usuario], [Nombre], [Correo], [Contrasena], [Rol]) VALUES (13, N'Laura Sanchez', N'laura.sanchez@brainbro.com', N'prof001', N'Profesor')
INSERT [dbo].[RegistroUsuario] ([ID_Usuario], [Nombre], [Correo], [Contrasena], [Rol]) VALUES (14, N'Gloria Martinez', N'gloria.martinez@brainbro.com', N'prof005', N'Profesor')
INSERT [dbo].[RegistroUsuario] ([ID_Usuario], [Nombre], [Correo], [Contrasena], [Rol]) VALUES (15, N'Patricia Diaz', N'patricia.diaz@brainbro.com', N'prof003', N'Profesor')
INSERT [dbo].[RegistroUsuario] ([ID_Usuario], [Nombre], [Correo], [Contrasena], [Rol]) VALUES (21, N'Alberto Ramirez', N'alberto.ramirez@brainbro.com', N'pad001', N'Padre')
INSERT [dbo].[RegistroUsuario] ([ID_Usuario], [Nombre], [Correo], [Contrasena], [Rol]) VALUES (22, N'Claudia Perez', N'claudia.perez@brainbro.com', N'pad002', N'Padre')
INSERT [dbo].[RegistroUsuario] ([ID_Usuario], [Nombre], [Correo], [Contrasena], [Rol]) VALUES (23, N'Fernando Torres', N'fernando.torres@brainbro.com', N'pad003', N'Padre')
INSERT [dbo].[RegistroUsuario] ([ID_Usuario], [Nombre], [Correo], [Contrasena], [Rol]) VALUES (100, N'Carlos Mendoza', N'carlos.mendoza@brainbro.com', N'coord123', N'Coordinador')
GO
ALTER TABLE [dbo].[RegistroUsuario]  WITH CHECK ADD CHECK  (([Rol]='Padre' OR [Rol]='Profesor' OR [Rol]='Estudiante' OR [Rol]='Coordinador'))
GO
