SET IDENTITY_INSERT [dbo].[Respuestas] ON 

INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (1, 1, N'25', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (2, 1, N'30', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (3, 1, N'35', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (4, 1, N'40', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (5, 2, N'8 cm2', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (6, 2, N'16 cm2', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (7, 2, N'12 cm2', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (8, 2, N'20 cm2', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (9, 3, N'5', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (10, 3, N'7', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (11, 3, N'10', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (12, 3, N'12', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (13, 4, N'4 lados', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (14, 4, N'5 lados', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (15, 4, N'6 lados', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (16, 4, N'8 lados', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (17, 5, N'2/4', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (18, 5, N'3/4', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (19, 5, N'1/3', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (20, 5, N'4/5', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (21, 6, N'La célula', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (22, 6, N'El tejido', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (23, 6, N'El órgano', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (24, 6, N'El átomo', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (25, 7, N'Pulmones', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (26, 7, N'Corazón', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (27, 7, N'Riñones', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (28, 7, N'Cerebro', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (29, 8, N'Marte', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (30, 8, N'Venus', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (31, 8, N'Júpiter', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (32, 8, N'Saturno', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (33, 9, N'Luz solar, agua y dióxido de carbono', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (34, 9, N'Solo oxígeno', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (35, 9, N'Solo minerales', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (36, 9, N'Calor artificial', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (37, 10, N'Sólido', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (38, 10, N'Líquido', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (39, 10, N'Gas', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (40, 10, N'Plasma', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (41, 11, N'Sistema circulatorio', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (42, 11, N'Sistema digestivo', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (43, 11, N'Sistema óseo', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (44, 11, N'Sistema muscular', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (45, 12, N'Contiene la información genética', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (46, 12, N'Produce energía', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (47, 12, N'Transporta sangre', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (48, 12, N'Forma huesos', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (49, 13, N'Energía solar', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (50, 13, N'Energía nuclear solamente', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (51, 13, N'Energía sonora', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (52, 13, N'Energía mecánica', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (53, 14, N'Conjunto de seres vivos y su ambiente', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (54, 14, N'Un solo animal', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (55, 14, N'Una célula', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (56, 14, N'Una molécula', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (57, 15, N'Coordinar las funciones del cuerpo', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (58, 15, N'Digestionar alimentos', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (59, 15, N'Producir sangre', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (60, 15, N'Mover músculos únicamente', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (61, 16, N'La herencia de características', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (62, 16, N'Los planetas', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (63, 16, N'Los minerales', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (64, 16, N'El clima', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (65, 17, N'Ley de Newton', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (66, 17, N'Ley de Boyle', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (67, 17, N'Ley de Ohm', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (68, 17, N'Ley de Mendel', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (69, 18, N'Una célula con núcleo definido', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (70, 18, N'Una bacteria solamente', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (71, 18, N'Un virus', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (72, 18, N'Un mineral', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (73, 19, N'H2O', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (74, 19, N'CO2', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (75, 19, N'O2', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (76, 19, N'NaCl', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (77, 20, N'Charles Darwin', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (78, 20, N'Albert Einstein', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (79, 20, N'Isaac Newton', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (80, 20, N'Galileo Galilei', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (81, 21, N'20', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (82, 21, N'18', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (83, 21, N'22', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (84, 21, N'24', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (85, 22, N'6', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (86, 22, N'9', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (87, 22, N'12', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (88, 22, N'3', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (89, 23, N'10 cm', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (90, 23, N'20 cm', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (91, 23, N'25 cm', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (92, 23, N'15 cm', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (93, 24, N'75%', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (94, 24, N'25%', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (95, 24, N'50%', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (96, 24, N'100%', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (97, 25, N'17', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (98, 25, N'3', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (99, 25, N'7', 0)
GO
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (100, 25, N'10', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (101, 26, N'10', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (102, 26, N'5', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (103, 26, N'20', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (104, 26, N'2', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (105, 27, N'25 cm²', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (106, 27, N'50 cm²', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (107, 27, N'15 cm²', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (108, 27, N'10 cm²', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (109, 28, N'Número entero', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (110, 28, N'Número negativo', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (111, 28, N'Número decimal', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (112, 28, N'Número imaginario', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (113, 29, N'0', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (114, 29, N'1', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (115, 29, N'-1', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (116, 29, N'2', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (117, 30, N'Propiedad conmutativa', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (118, 30, N'Propiedad distributiva', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (119, 30, N'Propiedad asociativa', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (120, 30, N'Propiedad inversa', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (121, 31, N'5 y -5', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (122, 31, N'5 solamente', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (123, 31, N'25', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (124, 31, N'0', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (125, 32, N'La relación entre circunferencia y diámetro', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (126, 32, N'Una operación matemática', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (127, 32, N'Un tipo de número', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (128, 32, N'Una ecuación', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (129, 33, N'Relación entre variables', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (130, 33, N'Una figura geométrica', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (131, 33, N'Un número primo', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (132, 33, N'Una medida', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (133, 34, N'30', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (134, 34, N'15', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (135, 34, N'50', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (136, 34, N'100', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (137, 35, N'La relación entre álgebra y geometría', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (138, 35, N'Los números naturales', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (139, 35, N'Las operaciones básicas', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (140, 35, N'Los porcentajes', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (141, 36, N'El estudio de las sociedades humanas, su historia y organización', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (142, 36, N'Solo el estudio de animales', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (143, 36, N'El estudio de números y operaciones', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (144, 36, N'El estudio de fenómenos químicos', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (145, 37, N'La civilización Mesopotámica', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (146, 37, N'La civilización moderna', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (147, 37, N'La civilización americana actual', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (148, 37, N'La civilización industrial', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (149, 38, N'Grupo de personas que comparten un espacio y características comunes', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (150, 38, N'Un solo individuo', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (151, 38, N'Un objeto histórico', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (152, 38, N'Un territorio sin habitantes', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (153, 39, N'Representar lugares y ubicaciones de la Tierra', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (154, 39, N'Medir únicamente la temperatura', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (155, 39, N'Reemplazar los libros', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (156, 39, N'Mostrar solo imágenes', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (157, 40, N'Un sistema donde los ciudadanos participan en las decisiones del país', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (158, 40, N'Un sistema donde una persona tiene todo el poder', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (159, 40, N'Un tipo de economía', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (160, 40, N'Una religión', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (161, 41, N'Europa', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (162, 41, N'África únicamente', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (163, 41, N'América del Sur', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (164, 41, N'Oceanía', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (165, 42, N'Un movimiento político y social ocurrido en Francia en 1789', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (166, 42, N'Una guerra mundial', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (167, 42, N'Una civilización antigua', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (168, 42, N'Un descubrimiento científico', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (169, 43, N'El conjunto de normas fundamentales de un país', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (170, 43, N'Una lista de habitantes', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (171, 43, N'Un mapa del territorio', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (172, 43, N'Un tipo de moneda', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (173, 44, N'La producción, distribución y consumo de bienes y servicios', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (174, 44, N'Solo la compra de alimentos', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (175, 44, N'El estudio del clima', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (176, 44, N'La creación de mapas', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (177, 45, N'Administrar y organizar los recursos y normas del país', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (178, 45, N'Crear planetas', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (179, 45, N'Eliminar las leyes', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (180, 45, N'Controlar únicamente deportes', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (181, 46, N'La relación entre las personas y el espacio donde viven', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (182, 46, N'Solo los animales', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (183, 46, N'Los números naturales', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (184, 46, N'Los experimentos químicos', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (185, 47, N'El proceso mediante el cual Colombia dejó de depender de España', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (186, 47, N'La creación de internet', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (187, 47, N'Una revolución industrial', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (188, 47, N'Un cambio climático', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (189, 48, N'La condición de pertenecer a una sociedad con derechos y deberes', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (190, 48, N'Tener únicamente una profesión', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (191, 48, N'Vivir en otro planeta', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (192, 48, N'No tener responsabilidades', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (193, 49, N'La conexión e integración entre países a nivel mundial', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (194, 49, N'El aislamiento de países', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (195, 49, N'Una forma de gobierno', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (196, 49, N'Un fenómeno natural', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (197, 50, N'Proteger la dignidad y libertades de las personas', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (198, 50, N'Eliminar las leyes', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (199, 50, N'Crear conflictos', 0)
GO
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (200, 50, N'Controlar los recursos naturales', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (201, 51, N'Una palabra que nombra personas, lugares, animales o cosas', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (202, 51, N'Una acción realizada por alguien', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (203, 51, N'Una característica de un objeto', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (204, 51, N'Una emoción', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (205, 52, N'Indicar acciones, estados o procesos', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (206, 52, N'Nombrar objetos únicamente', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (207, 52, N'Describir colores solamente', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (208, 52, N'Reemplazar los sustantivos', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (209, 53, N'Un conjunto de palabras con sentido completo', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (210, 53, N'Una lista de números', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (211, 53, N'Un dibujo sin palabras', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (212, 53, N'Una palabra aislada siempre', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (213, 54, N'Contento', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (214, 54, N'Triste', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (215, 54, N'Enojado', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (216, 54, N'Preocupado', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (217, 55, N'Texto narrativo', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (218, 55, N'Texto matemático', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (219, 55, N'Texto científico únicamente', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (220, 55, N'Texto publicitario siempre', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (221, 56, N'Una comparación entre dos elementos usando una relación imaginaria', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (222, 56, N'Una operación matemática', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (223, 56, N'Una regla ortográfica', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (224, 56, N'Un tipo de oración', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (225, 57, N'Inicio, desarrollo y desenlace', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (226, 57, N'Título y firma solamente', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (227, 57, N'Preguntas y respuestas', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (228, 57, N'Imágenes y gráficos únicamente', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (229, 58, N'Modificar o describir las características de un sustantivo', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (230, 58, N'Indicar acciones', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (231, 58, N'Reemplazar verbos', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (232, 58, N'Crear preguntas', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (233, 59, N'La información más importante que comunica el texto', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (234, 59, N'El título solamente', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (235, 59, N'Una palabra desconocida', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (236, 59, N'La última frase siempre', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (237, 60, N'Presenta una opinión defendida con argumentos', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (238, 60, N'Solo cuenta una historia ficticia', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (239, 60, N'Solo presenta datos numéricos', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (240, 60, N'No tiene ninguna estructura', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (241, 61, N'Un texto donde el autor analiza y desarrolla una idea o tema', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (242, 61, N'Un texto sin contenido', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (243, 61, N'Una lista de palabras', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (244, 61, N'Una noticia solamente', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (245, 62, N'Hipérbole', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (246, 62, N'Símil', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (247, 62, N'Descripción', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (248, 62, N'Diálogo', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (249, 63, N'La idea o postura que el autor defiende', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (250, 63, N'El título del texto', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (251, 63, N'La conclusión únicamente', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (252, 63, N'El número de páginas', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (253, 64, N'El literal expresa un significado directo y el figurado uno simbólico', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (254, 64, N'Son exactamente iguales', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (255, 64, N'El figurado no tiene significado', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (256, 64, N'El literal siempre es falso', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (257, 65, N'Romanticismo', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (258, 65, N'Realismo mágico', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (259, 65, N'Vanguardismo', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (260, 65, N'Clasicismo antiguo', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (261, 66, N'Una máquina electrónica que procesa información', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (262, 66, N'Un tipo de programa únicamente', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (263, 66, N'Una conexión de internet', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (264, 66, N'Un dispositivo de almacenamiento solamente', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (265, 67, N'Ingresar datos y escribir información', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (266, 67, N'Mostrar imágenes solamente', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (267, 67, N'Guardar energía', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (268, 67, N'Conectar redes', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (269, 68, N'Los componentes físicos de un computador', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (270, 68, N'Los programas instalados', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (271, 68, N'Los usuarios del sistema', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (272, 68, N'Los archivos de internet', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (273, 69, N'Un conjunto de datos almacenados digitalmente', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (274, 69, N'Un objeto físico', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (275, 69, N'Una conexión eléctrica', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (276, 69, N'Un programa antivirus', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (277, 70, N'Administrar los recursos del computador y permitir ejecutar programas', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (278, 70, N'Crear solamente documentos', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (279, 70, N'Reemplazar el hardware', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (280, 70, N'Aumentar el tamaño del monitor', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (281, 71, N'Conjunto de computadores conectados para compartir información', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (282, 71, N'Un solo computador apagado', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (283, 71, N'Un programa de dibujo', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (284, 71, N'Un dispositivo externo', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (285, 72, N'Almacenar temporalmente información para que el computador funcione más rápido', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (286, 72, N'Guardar archivos permanentemente', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (287, 72, N'Conectar impresoras', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (288, 72, N'Crear páginas web', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (289, 73, N'Un sistema organizado para almacenar y gestionar información', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (290, 73, N'Un videojuego', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (291, 73, N'Un dispositivo físico', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (292, 73, N'Una red social', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (293, 74, N'HTML', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (294, 74, N'SQL únicamente', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (295, 74, N'Python únicamente', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (296, 74, N'Windows', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (297, 75, N'Proteger la información y los sistemas contra amenazas', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (298, 75, N'Eliminar todos los archivos', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (299, 75, N'Aumentar la velocidad del teclado', 0)
GO
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (300, 75, N'Crear imágenes digitales', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (301, 76, N'Un conjunto ordenado de pasos para resolver un problema', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (302, 76, N'Un tipo de computador', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (303, 76, N'Una imagen digital', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (304, 76, N'Un archivo de texto', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (305, 77, N'Una interfaz que permite la comunicación entre sistemas o aplicaciones', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (306, 77, N'Un dispositivo de almacenamiento', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (307, 77, N'Un lenguaje de programación solamente', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (308, 77, N'Un sistema operativo', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (309, 78, N'Almacenar, organizar y consultar información', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (310, 78, N'Crear únicamente diseños gráficos', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (311, 78, N'Reemplazar usuarios', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (312, 78, N'Controlar redes sociales', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (313, 79, N'Proceso de crear instrucciones que ejecuta un computador', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (314, 79, N'Proceso de ensamblar hardware solamente', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (315, 79, N'Crear documentos manualmente', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (316, 79, N'Conectar cables', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (317, 80, N'Structured Query Language', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (318, 80, N'System Quality Language', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (319, 80, N'Software Query Logic', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (320, 80, N'Simple Question Language', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (321, 81, N'Crear un proyecto o actividad para ofrecer productos o servicios', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (322, 81, N'Copiar exactamente un negocio existente', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (323, 81, N'No tener ningún objetivo', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (324, 81, N'Solo gastar dinero', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (325, 82, N'Creatividad, responsabilidad y capacidad de tomar decisiones', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (326, 82, N'No aceptar cambios', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (327, 82, N'Evitar aprender cosas nuevas', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (328, 82, N'Trabajar siempre solo', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (329, 83, N'Una propuesta de producto o servicio que puede generar valor', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (330, 83, N'Un gasto personal', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (331, 83, N'Una tarea escolar únicamente', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (332, 83, N'Un documento sin propósito', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (333, 84, N'Permite organizar objetivos, recursos y actividades', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (334, 84, N'Hace innecesario el trabajo', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (335, 84, N'Evita tomar decisiones', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (336, 84, N'Elimina todos los riesgos', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (337, 85, N'Colaborar con otras personas para lograr un objetivo común', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (338, 85, N'Trabajar sin comunicación', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (339, 85, N'Hacer todas las tareas solo', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (340, 85, N'Evitar compartir ideas', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (341, 86, N'Documento donde se describe un negocio, sus objetivos y estrategias', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (342, 86, N'Una lista de compras personales', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (343, 86, N'Un contrato laboral únicamente', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (344, 86, N'Un informe deportivo', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (345, 87, N'Persona que adquiere un producto o servicio', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (346, 87, N'Persona que fabrica únicamente productos', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (347, 87, N'Un empleado siempre', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (348, 87, N'Un proveedor de internet', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (349, 88, N'Crear nuevas ideas o mejorar productos y procesos', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (350, 88, N'Repetir siempre lo mismo', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (351, 88, N'Eliminar cambios', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (352, 88, N'Reducir la creatividad', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (353, 89, N'Elementos necesarios para que una empresa funcione', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (354, 89, N'Solo el dinero', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (355, 89, N'Solo los empleados', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (356, 89, N'Solo los productos', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (357, 90, N'Actuar de manera ética y responsable con la sociedad', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (358, 90, N'Ignorar las consecuencias de las decisiones', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (359, 90, N'Buscar únicamente beneficios personales', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (360, 90, N'No cumplir normas', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (361, 91, N'La forma en que una empresa crea, entrega y obtiene valor', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (362, 91, N'Un listado de empleados', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (363, 91, N'Una factura de compra', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (364, 91, N'Un diseño gráfico', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (365, 92, N'Estudiar clientes, competencia y necesidades del mercado', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (366, 92, N'Ignorar a los clientes', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (367, 92, N'Eliminar productos', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (368, 92, N'Evitar investigar', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (369, 93, N'Plan de acciones para alcanzar objetivos empresariales', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (370, 93, N'Una actividad sin organización', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (371, 93, N'Un gasto innecesario', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (372, 93, N'Una regla matemática', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (373, 94, N'Permite controlar ingresos, gastos y recursos económicos', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (374, 94, N'Evita tomar decisiones', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (375, 94, N'Elimina la necesidad de organización', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (376, 94, N'Solo sirve para empresas grandes', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (377, 95, N'Crear un negocio responsable con el ambiente y la sociedad', 1)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (378, 95, N'Usar recursos sin control', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (379, 95, N'Ignorar el futuro', 0)
INSERT [dbo].[Respuestas] ([ID_Respuesta], [ID_Pregunta], [Respuesta], [EsCorrecta]) VALUES (380, 95, N'Eliminar la planificación', 0)
SET IDENTITY_INSERT [dbo].[Respuestas] OFF
GO
